version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/SnapShot
hooks:
    ApplicationStop: 
    - location: application_stop.sh
      timeout: 800
    AfterInstall:
    - location: after_install.sh
      timeout: 1000
    ApplicationStart:
    - location: application_start.sh
      timeout: 10000
