version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/SnapShot
hooks:
    ApplicationStop: 
    - location: application_stop.sh
      timeout: 300
    ApplicationStart: 
    - location: application_start.sh
      timeout: 900
